spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/consome?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/consome?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: consome
    password: consome123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none  # 데이터베이스 스키마 자동 생성 설정 (none, update, create, create-drop) 추후 none으로 변경할것
    show-sql: true  # SQL 쿼리 로그 출력 여부
    format_sql: true
    type: trace
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8.x에 맞는 dialect 사용

  flyway:
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # 바인딩 파라미터 로그 출력
    #org.hibernate.type:trace

jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}